// Runs before every `ng build`/`ng serve` (see package.json's "start"
// and "build" scripts) to stamp the app's version number + build time
// into a generated file the app can import. Version comes from this
// package.json's own "version" field — bump that on every real release
// (e.g. 1.0.0 -> 1.1.0) so the "Deployed Version" dialog shows something
// meaningful to non-technical staff, unlike a raw commit hash/branch.
const fs = require('fs');
const path = require('path');

const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf8'));

const content = `// AUTO-GENERATED by scripts/generate-version.js on every build — do not
// edit by hand, your changes will be overwritten on the next build.
export const APP_VERSION = {
  version: ${JSON.stringify(pkg.version ?? '0.0.0')},
  buildTime: ${JSON.stringify(new Date().toISOString())},
};
`;

const outPath = path.join(__dirname, '..', 'src', 'environments', 'version.ts');
fs.writeFileSync(outPath, content);
console.log(`[generate-version] wrote ${outPath} (v${pkg.version})`);
